# Generated by Django 4.0.4 on 2022-05-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='job_title',
        ),
        migrations.AddField(
            model_name='contrato',
            name='job_title_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobtitle'),
        ),
    ]
