# Generated by Django 4.0.4 on 2022-05-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sex_associates_genre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associates',
            name='genre_id',
            field=models.ForeignKey(default='Femenino', on_delete=django.db.models.deletion.CASCADE, to='dashboard.sex'),
        ),
    ]
