# Generated by Django 4.0.4 on 2022-05-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_associates_genre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associates',
            old_name='genre_id',
            new_name='sex_id',
        ),
        migrations.RenameField(
            model_name='sex',
            old_name='genre',
            new_name='sex',
        ),
    ]
