# Generated by Django 4.0.4 on 2022-05-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_associates_sex_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_colleague',
            new_name='country_associate',
        ),
        migrations.RenameField(
            model_name='sex',
            old_name='sex',
            new_name='sex_associate',
        ),
    ]
