# Generated by Django 4.0.4 on 2022-05-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_country_colleague_country_country_associate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associates',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='associates',
            old_name='job_title_id',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='associates',
            old_name='sex_id',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='associates',
            old_name='status_id',
            new_name='status',
        ),
    ]
