# Generated by Django 4.0.4 on 2022-05-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_country_id_associates_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sex',
            old_name='sex_associate',
            new_name='sex',
        ),
    ]
