# Generated by Django 4.0.4 on 2022-05-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_sex_associate_sex_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_associate',
            new_name='country',
        ),
    ]
