# Generated by Django 4.0.4 on 2022-05-24 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_users_sex'),
        ('dashboard', '0011_rename_country_associate_country_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='associates',
            name='sex',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.AddField(
            model_name='associates',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.gender'),
        ),
    ]
