# Generated by Django 4.0.4 on 2022-05-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_country_associate_country_country'),
        ('authentication', '0002_users_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobtitle'),
        ),
    ]
