# Generated by Django 4.0.4 on 2022-05-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_job_title_users_job_title_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='job_title_id',
            new_name='job_title',
        ),
    ]
