# Generated by Django 4.0.4 on 2022-05-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_job_title_id_users_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
    ]
